#!/usr/bin/env bash
mvn package assembly:single |grep "\[INFO\] BUILD .*"
cp target/*-dependencies.jar ./turing.jar
if [[ -n "$1" ]];
then
java -jar turing.jar $1
else
java -jar turing.jar case1
java -jar turing.jar case2
java -jar turing.jar fuzzing-case
java -jar turing.jar long-case
java -jar turing.jar official-case
tar -cvf final.tar case1 case2 fuzzing-case long-case official-case
fi
